# Generated by Django 5.0.4 on 2024-04-20 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appkino', '0002_modelactor_photo_modeldirector_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelkino',
            name='podpiska',
        ),
        migrations.AddField(
            model_name='modelkino',
            name='podpiska',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='appkino.modelpodpiska', verbose_name='Подписка'),
        ),
    ]
